import type { Metadata } from "next"
import { Geist, Geist_Mono, Kantumruy_Pro } from "next/font/google"

import "./globals.css"
import AuthProvider from "@/providers/auth-provider"
import ThemeProvider from "@/providers/theme-provider"
import { Toaster as Sonner } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const kantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kantumruy.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Sonner richColors expand={true} position="top-right" />

          </ThemeProvider>
        </AuthProvider> 
      </body>
    </html>
  )
}
