export const Index = {
    "banner": {
        name: "banner",
        type: "registry:section",
        slug: "/blocks/banner",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/banner.png",
        number: "1",
    },
    "blog": {
        name: "blog",
        type: "registry:section",
        slug: "/blocks/blog",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/blog.png",
        number: "6",
    },
    "career": {
        name: "career",
        type: "registry:section",
        slug: "/blocks/career",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/career.png",
        number: "1",
    },
    "contact": {
        name: "contact",
        type: "registry:section",
        slug: "/blocks/contact",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/contact.png",
        number: "2",
    },
    "cta": {
        name: "cta",
        type: "registry:section",
        slug: "/blocks/cta",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/cta.png",
        number: "1",
    },
    "faq": {
        name: "faq",
        type: "registry:section",
        slug: "/blocks/faq",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/faq.png",
        number: "1",
    },
    "feature": {
        name: "feature",
        type: "registry:section",
        slug: "/blocks/feature",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/feature.png",
        number: "1",
    },
    "footer": {
        name: "footer",
        type: "registry:section",
        slug: "/blocks/footer",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/footer.png",
        number: "3",
    },
    "hero": {
        name: "hero",
        type: "registry:section",
        slug: "/blocks/hero",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/hero.png",
        number: "5",
    },
    "login": {
        name: "login",
        type: "registry:section",
        slug: "/blocks/login",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/login.png",
        number: "4",
    },
    "metrics": {
        name: "metrics",
        type: "registry:section",
        slug: "/blocks/metrics",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/metrics.png",
        number: "1",
    },
    "navbar": {
        name: "navbar",
        type: "registry:section",
        slug: "/blocks/navbar",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/navbar.png",
        number: "1",

    },
    "newsletter": {
        name: "newsletter",
        type: "registry:section",
        slug: "/blocks/newsletter",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/newsletter.png",
        number: "1",
    },
    "pricing": {
        name: "pricing",
        type: "registry:section",
        slug: "/blocks/pricing",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/pricing.png",
        number: "7",
    },
    "team": {
        name: "team",
        type: "registry:section",
        slug: "/blocks/team",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/team.png",
        number: "1",
    },
    "testimonial": {
        name: "testimonial",
        type: "registry:section",
        slug: "/blocks/testimonial",
        thumbnail: "https://res.cloudinary.com/dcxm3ccir/image/upload/v1753941711/testimonial.png",
        number: "1",
    },
}